#!/bin/bash
list=`cat ${MPAF}/scripts/package_list`
echo build all packages: $list
for i in $list; do
    source ${MPAF}/scripts/build_package $i "$@"
done 
if test -f ${MPAF}/analysis/bin/analysis
then
    now="$(date +'%Y-%m-%d-%I-%M-%S')"
    cmd=$(printf 'git tag %s_compiled' $now)
    eval $cmd
fi
